services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  cassandra:
    image: cassandra:4.1
    environment:
      CASSANDRA_CLUSTER_NAME: "log-cluster"
      CASSANDRA_START_RPC: "true"

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  cockroach:
    image: cockroachdb/cockroach:v23.2.9
    command: start-single-node --insecure
    ports:
      - "26257:26257"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deploy/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

  authsvc:
    build:
      context: .
      dockerfile: cmd/authsvc/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - cockroach
    volumes:
      - ./deploy/authsvc/config.yml:/etc/authsvc/config.yml:ro
    networks:
      - default

  gateway:
    build:
      context: .
      dockerfile: cmd/gateway/Dockerfile
    depends_on:
      - kafka
      - authsvc
    volumes:
      - ./deploy/gateway/config.yml:/etc/gateway/config.yml:ro
    ports:
      - "8081:8081"
    networks:
      - default

  processor:
    build:
      context: .
      dockerfile: cmd/processor/Dockerfile
    depends_on:
      - kafka
      - cassandra
      - clickhouse
    volumes:
      - ./deploy/processor/config.yml:/etc/processor/config.yml:ro
    ports:
      - "9100:9100"
    networks:
      - default

  querysvc:
    build:
      context: .
      dockerfile: cmd/querysvc/Dockerfile
    depends_on:
      - cockroach
      - clickhouse
      - cassandra
    volumes:
      - ./deploy/querysvc/config.yml:/etc/querysvc/config.yml:ro
    ports:
      - "8082:8082"
    networks:
      - default

networks:
  default:
    name: lognet
