// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: query.proto

package query

import (
	ingest "github.com/parishadmk/log-system-analysis/internal/api/ingest"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // JWT
	Filters       map[string]string      `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SearchRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SearchRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type EventSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LastSeen      int64                  `protobuf:"varint,2,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSummary) Reset() {
	*x = EventSummary{}
	mi := &file_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSummary) ProtoMessage() {}

func (x *EventSummary) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSummary.ProtoReflect.Descriptor instead.
func (*EventSummary) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{1}
}

func (x *EventSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventSummary) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *EventSummary) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventSummary        `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetEvents() []*EventSummary {
	if x != nil {
		return x.Events
	}
	return nil
}

type EventDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	EventName     string                 `protobuf:"bytes,3,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"` // optional paging cursor
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventDetailRequest) Reset() {
	*x = EventDetailRequest{}
	mi := &file_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDetailRequest) ProtoMessage() {}

func (x *EventDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDetailRequest.ProtoReflect.Descriptor instead.
func (*EventDetailRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{3}
}

func (x *EventDetailRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *EventDetailRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EventDetailRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *EventDetailRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type EventDetailResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Cursor string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// qualify with the package from log_ingest.proto
	Entry         *ingest.LogPayload `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventDetailResponse) Reset() {
	*x = EventDetailResponse{}
	mi := &file_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDetailResponse) ProtoMessage() {}

func (x *EventDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDetailResponse.ProtoReflect.Descriptor instead.
func (*EventDetailResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{4}
}

func (x *EventDetailResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *EventDetailResponse) GetEntry() *ingest.LogPayload {
	if x != nil {
		return x.Entry
	}
	return nil
}

var File_query_proto protoreflect.FileDescriptor

const file_query_proto_rawDesc = "" +
	"\n" +
	"\vquery.proto\x12\x05query\x1a\x10log_ingest.proto\"\xbd\x01\n" +
	"\rSearchRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12;\n" +
	"\afilters\x18\x03 \x03(\v2!.query.SearchRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\fEventSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tlast_seen\x18\x02 \x01(\x03R\blastSeen\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"=\n" +
	"\x0eSearchResponse\x12+\n" +
	"\x06events\x18\x01 \x03(\v2\x13.query.EventSummaryR\x06events\"\x80\x01\n" +
	"\x12EventDetailRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"event_name\x18\x03 \x01(\tR\teventName\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\"W\n" +
	"\x13EventDetailResponse\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12(\n" +
	"\x05entry\x18\x02 \x01(\v2\x12.ingest.LogPayloadR\x05entry2\x94\x01\n" +
	"\fQueryService\x12;\n" +
	"\fSearchEvents\x12\x14.query.SearchRequest\x1a\x15.query.SearchResponse\x12G\n" +
	"\x0eGetEventDetail\x12\x19.query.EventDetailRequest\x1a\x1a.query.EventDetailResponseB>Z<github.com/parishadmk/log-system-analysis/internal/api/queryb\x06proto3"

var (
	file_query_proto_rawDescOnce sync.Once
	file_query_proto_rawDescData []byte
)

func file_query_proto_rawDescGZIP() []byte {
	file_query_proto_rawDescOnce.Do(func() {
		file_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)))
	})
	return file_query_proto_rawDescData
}

var file_query_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_query_proto_goTypes = []any{
	(*SearchRequest)(nil),       // 0: query.SearchRequest
	(*EventSummary)(nil),        // 1: query.EventSummary
	(*SearchResponse)(nil),      // 2: query.SearchResponse
	(*EventDetailRequest)(nil),  // 3: query.EventDetailRequest
	(*EventDetailResponse)(nil), // 4: query.EventDetailResponse
	nil,                         // 5: query.SearchRequest.FiltersEntry
	(*ingest.LogPayload)(nil),   // 6: ingest.LogPayload
}
var file_query_proto_depIdxs = []int32{
	5, // 0: query.SearchRequest.filters:type_name -> query.SearchRequest.FiltersEntry
	1, // 1: query.SearchResponse.events:type_name -> query.EventSummary
	6, // 2: query.EventDetailResponse.entry:type_name -> ingest.LogPayload
	0, // 3: query.QueryService.SearchEvents:input_type -> query.SearchRequest
	3, // 4: query.QueryService.GetEventDetail:input_type -> query.EventDetailRequest
	2, // 5: query.QueryService.SearchEvents:output_type -> query.SearchResponse
	4, // 6: query.QueryService.GetEventDetail:output_type -> query.EventDetailResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_query_proto_init() }
func file_query_proto_init() {
	if File_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_query_proto_goTypes,
		DependencyIndexes: file_query_proto_depIdxs,
		MessageInfos:      file_query_proto_msgTypes,
	}.Build()
	File_query_proto = out.File
	file_query_proto_goTypes = nil
	file_query_proto_depIdxs = nil
}
